@if not exist generated_proto mkdir generated_proto

@echo Running Protocol Buffer Compiler on netmessages_public.proto...
@protoc\protoc.exe --proto_path=.\protos --proto_path=.\protobuf\src --cpp_out=.\generated_proto .\protos\netmessages_public.proto

@echo Running Protocol Buffer Compiler on cstrike15_usermessages_public.proto...
@protoc\protoc.exe --proto_path=.\protos --proto_path=.\protobuf\src --cpp_out=.\generated_proto .\protos\cstrike15_usermessages_public.proto

@echo Running Protocol Buffer Compiler on cstrike15_gcmessages.proto...
@protoc\protoc.exe --proto_path=.\protos --proto_path=.\protobuf\src --cpp_out=.\generated_proto .\protos\cstrike15_gcmessages.proto

@echo Running Protocol Buffer Compiler on steammessages.proto...
@protoc\protoc.exe --proto_path=.\protos --proto_path=.\protobuf\src --cpp_out=.\generated_proto .\protos\steammessages.proto
